### ISSUE TITLE
Snappy error on arm / ubuntu

### ISSUE THREAD

**Issue by wolfeidau** [davecheney/autobench#38]
Just trying to run the full suite on 13.04 arm and i get the following error when i run `make`.

```
#snappy
benchcmp: no repeated benchmarks
make: *** [snappy] Error 1
```

Also `make float` doesn't seem to do anything.

```
make float
make: *** No rule to make target `float'.  Stop.
```

Any ideas on how to get this snappy segment of benchmarks working?

**Comment by davecheney** [comment]
Is your working copy out of date ?

If you want to skip the float benchmarks, just remove `float` from Makefile
line 26

It is possible that one of the snappy benchmarks failed to run, have a look
in work/

**Comment by wolfeidau** [comment]
So firstly clean checkout this morning.

Float stuff was an observation, it is listed in your readme but doesn't exist..

So this explains why snappy no work.

```
BenchmarkWordsDecode1e3 --- FAIL: BenchmarkWordsDecode1e3
    snappy_test.go:108: failed reading /usr/share/dict/words: open /usr/share/dict/words: no such file or directory
```

To fix.

```
sudo apt-get install wbritish
```

or

```
sudo apt-get install wamerican
```

**Comment by davecheney** [comment]
Wow, I never considerde that the snappy benchmarks needed that file

This should fix it

% dpkg -S /usr/share/dict/words
diversion by dictionaries-common from: /usr/share/dict/words
diversion by dictionaries-common to:
/usr/share/dict/words.pre-dictionaries-common
dictionaries-common, wamerican: /usr/share/dict/words

try

sudo apt-get install dictionaries-common

**Comment by wolfeidau** [comment]
Aha good point, I should have asked dpkg first.

**Comment by wolfeidau** [comment]
Seems I manage to oom.

```
/home/ubuntu/autobench/work/go1.1.2/bin/go test  -test.run=XXX -test.bench=. bench/floats > /home/ubuntu/autobench/work/floats-go1.1.2.txt
testing: warning: no tests to run
fatal error: runtime: out of memory

goroutine 14 [running]:
[fp=0x404d9d40] runtime.throw(0x1a516f)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/panic.c:473 +0x50
[fp=0x404d9d68] runtime.SysMap(0x28190000, 0x4c50000)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/mem_linux.c:131 +0xb8
[fp=0x404d9d88] runtime.MHeap_SysAlloc(0x40074000, 0x4c50000)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/zmalloc_linux_arm.c:360 +0x130
[fp=0x404d9dbc] MHeap_Grow(0x40074000, 0x4c50)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/mheap.c:224 +0x50
[fp=0x404d9df0] MHeap_AllocLocked(0x40074000, 0x4c4c, 0x0)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/mheap.c:108 +0x354
[fp=0x404d9e18] runtime.MHeap_Alloc(0x40074000, 0x4c4c, 0x0, 0x1, 0x1, ...)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/mheap.c:77 +0x50
[fp=0x404d9e48] runtime.mallocgc(0x4c4b400, 0x1, 0x1, 0x1)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/zmalloc_linux_arm.c:58 +0x2e0
[fp=0x404d9e74] cnew(0xe2518, 0x989680, 0x1)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/zmalloc_linux_arm.c:655 +0xdc
[fp=0x404d9e84] runtime.cnewarray(0xe2518, 0x989680)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/zmalloc_linux_arm.c:673 +0x38
[fp=0x404d9e90] makeslice1(0xdf300, 0x989680, 0x989680, 0x404d9ec8)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/slice.c:53 +0x44
[fp=0x404d9eb0] runtime.makeslice(0xdf300, 0x989680, 0x0, 0x989680, 0x0, ...)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/slice.c:34 +0x194
[fp=0x404d9eec] bench/floats.RandomSlice(0x989680, 0x2339b000, 0x989680, 0x989680)
    /home/ubuntu/autobench/src/bench/floats/floats_test.go:97 +0x50
[fp=0x404d9f68] bench/floats.BenchmarkAddFourHuge(0x10236840)
    /home/ubuntu/autobench/src/bench/floats/floats_test.go:204 +0x84
[fp=0x404d9f70] testing.(*B).runN(0x10236840, 0x1)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/benchmark.go:119 +0x94
[fp=0x404d9fd0] testing.(*B).launch(0x10236840)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/benchmark.go:187 +0x80
[fp=0x404d9fd4] runtime.goexit()
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/runtime/proc.c:1223
created by testing.(*B).run
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/benchmark.go:167 +0x40

goroutine 1 [chan receive]:
testing.(*B).run(0x10236840, 0x3, 0x404cbdf0, 0x1, 0x1, ...)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/benchmark.go:168 +0x5c
testing.RunBenchmarks(0x1229f4, 0x1a5398, 0x14, 0x14)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/benchmark.go:300 +0x4d8
testing.Main(0x1229f4, 0x1a8298, 0x0, 0x0, 0x1a5398, ...)
    /home/ubuntu/autobench/work/go1.1.2/src/pkg/testing/testing.go:373 +0x180
main.main()
    bench/floats/_test/_testmain.go:81 +0x94
make: *** [/home/ubuntu/autobench/work/floats-go1.1.2.txt] Error 1
```

Free is.

```
             total       used       free     shared    buffers     cached
Mem:           495        115        379          0          5         27
-/+ buffers/cache:         82        413
Swap:            0          0          0
```

Will stop everything, clean and run again.

**Comment by davecheney** [comment]
Add some swap, you probably won't need it, but it'll make the test pass.

**Comment by wolfeidau** [comment]
Just shut down some other processes and all passed.

Cheers.

**Comment by davecheney** [comment]
I hit this problem on linux/386 as well. Reopening as a reminder to add something to README.
